//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scarab {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Scarab.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MI_InstallText_Installed {
            get {
                return ResourceManager.GetString("MI_InstallText_Installed", resourceCulture);
            }
        }
        
        internal static string MI_InstallText_NotInstalled {
            get {
                return ResourceManager.GetString("MI_InstallText_NotInstalled", resourceCulture);
            }
        }
        
        internal static string MLVM_ApiButtonText_DisableAPI {
            get {
                return ResourceManager.GetString("MLVM_ApiButtonText_DisableAPI", resourceCulture);
            }
        }
        
        internal static string MLVM_ApiButtonText_EnableAPI {
            get {
                return ResourceManager.GetString("MLVM_ApiButtonText_EnableAPI", resourceCulture);
            }
        }
        
        internal static string MLVM_ApiButtonText_ToggleAPI {
            get {
                return ResourceManager.GetString("MLVM_ApiButtonText_ToggleAPI", resourceCulture);
            }
        }
        
        internal static string MLVM_ChangePathAsync_Msgbox_Text {
            get {
                return ResourceManager.GetString("MLVM_ChangePathAsync_Msgbox_Text", resourceCulture);
            }
        }
        
        internal static string MLVM_ChangePathAsync_Msgbox_Title {
            get {
                return ResourceManager.GetString("MLVM_ChangePathAsync_Msgbox_Title", resourceCulture);
            }
        }
        
        internal static string MLVM_DisplayHashMismatch_Msgbox_Text {
            get {
                return ResourceManager.GetString("MLVM_DisplayHashMismatch_Msgbox_Text", resourceCulture);
            }
        }
        
        internal static string MLVM_DisplayHashMismatch_Msgbox_Title {
            get {
                return ResourceManager.GetString("MLVM_DisplayHashMismatch_Msgbox_Title", resourceCulture);
            }
        }
        
        internal static string MLVM_DisplayNetworkError_Msgbox_Text {
            get {
                return ResourceManager.GetString("MLVM_DisplayNetworkError_Msgbox_Text", resourceCulture);
            }
        }
        
        internal static string MLVM_DisplayNetworkError_Msgbox_Title {
            get {
                return ResourceManager.GetString("MLVM_DisplayNetworkError_Msgbox_Title", resourceCulture);
            }
        }
        
        internal static string MLVM_InternalUpdateInstallAsync_Msgbox_W_Text {
            get {
                return ResourceManager.GetString("MLVM_InternalUpdateInstallAsync_Msgbox_W_Text", resourceCulture);
            }
        }
        
        internal static string MLVM_InternalUpdateInstallAsync_Msgbox_W_Title {
            get {
                return ResourceManager.GetString("MLVM_InternalUpdateInstallAsync_Msgbox_W_Title", resourceCulture);
            }
        }
        
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Error {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Error", resourceCulture);
            }
        }
        
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Text {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Text", resourceCulture);
            }
        }
        
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Title {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Title", resourceCulture);
            }
        }
        
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Timeout {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Timeout", resourceCulture);
            }
        }
        
        internal static string MWVM_OutOfDate_GetLatest {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_GetLatest", resourceCulture);
            }
        }
        
        internal static string MWVM_OutOfDate_ContinueAnyways {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_ContinueAnyways", resourceCulture);
            }
        }
        
        internal static string MWVM_OutOfDate_Title {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_Title", resourceCulture);
            }
        }
        
        internal static string MWVM_OutOfDate_Message {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_Message", resourceCulture);
            }
        }
        
        internal static string MWVM_Warning {
            get {
                return ResourceManager.GetString("MWVM_Warning", resourceCulture);
            }
        }
        
        internal static string MWVM_InvalidSavedPath_Message {
            get {
                return ResourceManager.GetString("MWVM_InvalidSavedPath_Message", resourceCulture);
            }
        }
        
        internal static string MWVM_Info {
            get {
                return ResourceManager.GetString("MWVM_Info", resourceCulture);
            }
        }
        
        internal static string MWVM_UnableToDetect_Message {
            get {
                return ResourceManager.GetString("MWVM_UnableToDetect_Message", resourceCulture);
            }
        }
        
        internal static string MWVM_DetectedPath_Title {
            get {
                return ResourceManager.GetString("MWVM_DetectedPath_Title", resourceCulture);
            }
        }
        
        internal static string MWVM_DetectedPath_Message {
            get {
                return ResourceManager.GetString("MWVM_DetectedPath_Message", resourceCulture);
            }
        }
        
        internal static string XAML_ChangPath {
            get {
                return ResourceManager.GetString("XAML_ChangPath", resourceCulture);
            }
        }
        
        internal static string XAML_Dependencies {
            get {
                return ResourceManager.GetString("XAML_Dependencies", resourceCulture);
            }
        }
        
        internal static string XAML_Donate {
            get {
                return ResourceManager.GetString("XAML_Donate", resourceCulture);
            }
        }
        
        internal static string XAML_ModsFilter_All {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_All", resourceCulture);
            }
        }
        
        internal static string XAML_ModsFilter_Enabled {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_Enabled", resourceCulture);
            }
        }
        
        internal static string XAML_ModsFilter_Installed {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_Installed", resourceCulture);
            }
        }
        
        internal static string XAML_ModsFilter_OutOfDate {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_OutOfDate", resourceCulture);
            }
        }
        
        internal static string XAML_OpenMods {
            get {
                return ResourceManager.GetString("XAML_OpenMods", resourceCulture);
            }
        }
        
        internal static string XAML_Repository {
            get {
                return ResourceManager.GetString("XAML_Repository", resourceCulture);
            }
        }
        
        internal static string XAML_SearchMark {
            get {
                return ResourceManager.GetString("XAML_SearchMark", resourceCulture);
            }
        }
        
        internal static string XAML_UpdateAPI {
            get {
                return ResourceManager.GetString("XAML_UpdateAPI", resourceCulture);
            }
        }
        
        internal static string XAML_Version {
            get {
                return ResourceManager.GetString("XAML_Version", resourceCulture);
            }
        }
        
        internal static string XAML_Integrations {
            get {
                return ResourceManager.GetString("XAML_Integrations", resourceCulture);
            }
        }
        
        internal static string XAML_Tags {
            get {
                return ResourceManager.GetString("XAML_Tags", resourceCulture);
            }
        }
        
        internal static string XAML_On {
            get {
                return ResourceManager.GetString("XAML_On", resourceCulture);
            }
        }
        
        internal static string XAML_Off {
            get {
                return ResourceManager.GetString("XAML_Off", resourceCulture);
            }
        }
        
        internal static string XAML_Update {
            get {
                return ResourceManager.GetString("XAML_Update", resourceCulture);
            }
        }
        
        internal static string PU_NoSelect {
            get {
                return ResourceManager.GetString("PU_NoSelect", resourceCulture);
            }
        }
        
        internal static string PU_NoSelectMac {
            get {
                return ResourceManager.GetString("PU_NoSelectMac", resourceCulture);
            }
        }
        
        internal static string PU_InvalidPathHeader {
            get {
                return ResourceManager.GetString("PU_InvalidPathHeader", resourceCulture);
            }
        }
        
        internal static string PU_InvalidAppHeader {
            get {
                return ResourceManager.GetString("PU_InvalidAppHeader", resourceCulture);
            }
        }
        
        internal static string PU_InvalidPath {
            get {
                return ResourceManager.GetString("PU_InvalidPath", resourceCulture);
            }
        }
        
        internal static string PU_InvalidApp {
            get {
                return ResourceManager.GetString("PU_InvalidApp", resourceCulture);
            }
        }
        
        internal static string PU_SelectPath {
            get {
                return ResourceManager.GetString("PU_SelectPath", resourceCulture);
            }
        }
        
        internal static string PU_InvalidPathTitle {
            get {
                return ResourceManager.GetString("PU_InvalidPathTitle", resourceCulture);
            }
        }
        
        internal static string PU_SelectApp {
            get {
                return ResourceManager.GetString("PU_SelectApp", resourceCulture);
            }
        }
        
        internal static string XAML_ModsFilter_OutOfDate_Update {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_OutOfDate_Update", resourceCulture);
            }
        }
        
        internal static string NOTIFY_Installed {
            get {
                return ResourceManager.GetString("NOTIFY_Installed", resourceCulture);
            }
        }
        
        internal static string NOTIFY_Updated {
            get {
                return ResourceManager.GetString("NOTIFY_Updated", resourceCulture);
            }
        }
        
        internal static string NOTIFY_Uninstalled {
            get {
                return ResourceManager.GetString("NOTIFY_Uninstalled", resourceCulture);
            }
        }
    }
}
