global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.Reactive.Disposables;
global using System.Reactive;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.ReactiveUI;
global using Avalonia.Threading;
global using DynamicData;
global using DynamicData.Binding;
global using JetBrains.Annotations;
global using Microsoft.Extensions.Logging;
global using PropertyChanged.SourceGenerator;
global using ReactiveUI;
global using Scarab.Extensions;
global using Scarab.Interfaces;
global using Scarab.Models;
global using Scarab.Services;
global using Scarab.Util;
global using Scarab.ViewModels;
global using Serilog;
global using Notification = Avalonia.Controls.Notifications.Notification;
global using ILogger = Microsoft.Extensions.Logging.ILogger;